CREATE TABLE IF NOT EXISTS `audit_operation_event` (
  `id` bigint NOT NULL,
  `actor_user_id` bigint DEFAULT NULL,
  `module_code` varchar(64) NOT NULL,
  `action_code` varchar(64) NOT NULL,
  `target_type` varchar(64) DEFAULT NULL,
  `target_id` bigint DEFAULT NULL,
  `request_method` varchar(16) NOT NULL,
  `request_uri` varchar(255) NOT NULL,
  `request_summary` text,
  `response_summary` text,
  `result_status` varchar(32) NOT NULL,
  `duration_ms` int DEFAULT NULL,
  `ip` varchar(64) DEFAULT NULL,
  `trace_id` varchar(64) DEFAULT NULL,
  `request_id` varchar(64) DEFAULT NULL,
  `event_time` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_audit_operation_event_actor_user_id` (`actor_user_id`),
  KEY `idx_audit_operation_event_module_code` (`module_code`),
  KEY `idx_audit_operation_event_target_type` (`target_type`),
  KEY `idx_audit_operation_event_event_time` (`event_time`),
  KEY `idx_audit_operation_event_result_status` (`result_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
