CREATE TABLE IF NOT EXISTS `file_asset` (
  `id` bigint NOT NULL,
  `file_code` varchar(64) NOT NULL,
  `original_name` varchar(255) NOT NULL,
  `storage_name` varchar(255) NOT NULL,
  `category_code` varchar(64) DEFAULT NULL,
  `file_ext` varchar(32) DEFAULT NULL,
  `mime_type` varchar(128) NOT NULL,
  `size_bytes` bigint NOT NULL,
  `storage_provider` varchar(32) NOT NULL,
  `bucket_name` varchar(128) DEFAULT NULL,
  `object_key` varchar(255) DEFAULT NULL,
  `checksum` varchar(128) DEFAULT NULL,
  `visibility` varchar(32) NOT NULL,
  `uploader_user_id` bigint DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `remark` varchar(500) DEFAULT NULL,
  `content_blob` longblob,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_asset_file_code` (`file_code`),
  KEY `idx_file_asset_category_code` (`category_code`),
  KEY `idx_file_asset_uploader_user_id` (`uploader_user_id`),
  KEY `idx_file_asset_object_key` (`object_key`),
  KEY `idx_file_asset_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
