/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('antdv-next')['Alert']
    AApp: typeof import('antdv-next')['App']
    AAvatar: typeof import('antdv-next')['Avatar']
    ABadge: typeof import('antdv-next')['Badge']
    AButton: typeof import('antdv-next')['Button']
    ACard: typeof import('antdv-next')['Card']
    ACheckbox: typeof import('antdv-next')['Checkbox']
    ACheckboxGroup: typeof import('antdv-next')['CheckboxGroup']
    ACol: typeof import('antdv-next')['Col']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADescriptions: typeof import('antdv-next')['Descriptions']
    ADescriptionsItem: typeof import('antdv-next')['DescriptionsItem']
    ADrawer: typeof import('antdv-next')['Drawer']
    ADropdown: typeof import('antdv-next')['Dropdown']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputNumber: typeof import('antdv-next')['InputNumber']
    AMenu: typeof import('antdv-next')['Menu']
    AMenuItem: typeof import('antdv-next')['MenuItem']
    AModal: typeof import('antdv-next')['Modal']
    APagination: typeof import('antdv-next')['Pagination']
    APopover: typeof import('antdv-next')['Popover']
    ARadio: typeof import('antdv-next')['Radio']
    ARadioGroup: typeof import('antdv-next')['RadioGroup']
    ARangePicker: typeof import('antdv-next')['DateRangePicker']
    ARow: typeof import('antdv-next')['Row']
    ASelect: typeof import('antdv-next')['Select']
    ASelectOption: typeof import('antdv-next')['SelectOption']
    ASpace: typeof import('antdv-next')['Space']
    ASubMenu: typeof import('antdv-next')['SubMenu']
    ASwitch: typeof import('antdv-next')['Switch']
    ATable: typeof import('antdv-next')['Table']
    ATag: typeof import('antdv-next')['Tag']
    ATextarea: typeof import('antdv-next')['TextArea']
    ATooltip: typeof import('antdv-next')['Tooltip']
    ATree: typeof import('antdv-next')['Tree']
    ATreeSelect: typeof import('antdv-next')['TreeSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
