server:
  port: 8004
  servlet:
    context-path: /
  compression:
    enabled: true

spring:
  application:
    name: upms
  profiles:
    active: @profiles.active@
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    encoding: UTF-8
    validate-on-migrate: true
    out-of-order: false
    placeholder-replacement: false

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  is-read-header: true
  is-read-cookie: false
  is-read-body: false
  is-write-header: false
  timeout: 2592000
  active-timeout: -1
  is-concurrent: false
  is-share: false
  is-log: false

logging:
  level:
    root: info
    org.redisson: warn
    com.zaxxer.hikari: warn
    net.junanw.upms: debug

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  default-flat-param-object: true
  override-with-generic-response: false
